#
# These are the same as the defaults.
#
quarkus.package.jar.type=fast-jar
quarkus.http.port=8080
#
# https://quarkus.io/guides/tls-registry-reference#key-stores
quarkus.tls.key-store.p12.path=/keystore.p12
quarkus.tls.key-store.p12.password=${SERVER_KEYSTORE_PASSWORD}
quarkus.tls.key-store.p12.alias=server
quarkus.tls.key-store.p12.alias-password=${SERVER_KEY_PASSWORD}